"""aaaa

Revision ID: 087a31ae3a42
Revises: 
Create Date: 2017-02-10 16:59:54.028106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087a31ae3a42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('texts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('texts', sa.Column('title', sa.Text(), nullable=True))
    op.create_index(op.f('ix_texts_timestamp'), 'texts', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'location')
    op.drop_column('users', 'about_me')
    op.drop_index(op.f('ix_texts_timestamp'), table_name='texts')
    op.drop_column('texts', 'title')
    op.drop_column('texts', 'timestamp')
    op.drop_column('texts', 'body')
    # ### end Alembic commands ###
