"""txt

Revision ID: 837a7d3a3c95
Revises: d17a7a2dc845
Create Date: 2017-02-12 21:49:16.877357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837a7d3a3c95'
down_revision = 'd17a7a2dc845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('txt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'txt')
    # ### end Alembic commands ###
